### PR TITLE
feat: Made changes to new homepage

### PR DESCRIPTION
**Pull request by dwaldon21**
# Pull request

**Resolves:** #65

### CODE REVIEW

**Comment by XxXgamerguyXxX** [comment]
This fails pytest.

**Comment by XxXgamerguyXxX** [comment]
Looks good to me.

**Comment by XxXgamerguyXxX** [comment]
We are adding issue #98 to this PR as well so until those pushes come in this should not be looked at.

**Comment by XxXgamerguyXxX** [comment]
Looks good.

**Comment by asmitakarandikar** [comment]
Looks good, just add a text box/something the form results show after clicking the submit button for all of the submit buttons. Like Paige said, the UI should visually show the results if any. Additionally, for the file upload and metadata comparison, include a text box that shows the user if there are any differences.

**Comment by asmitakarandikar** [comment]
I also think the webpage would look cleaner if the forms were centered on the page.

**Comment by asmitakarandikar** [comment]
Looks good to me!

**Review by tclasen — APPROVED** [review]

**Pull request merged**
